version: '3'

services:
  app:
    image: registry.cn-shenzhen.aliyuncs.com/luler/gradio_base
    #    build:
    #      context: .
    #      dockerfile: Dockerfile
    restart: always
    ports:
      - 7860:7860
    volumes:
      - .:/app
#    environment:
#      - MYSTICAI_API_KEY=